camsaul/toucan2

test/toucan2/tools/after_insert_test.clj, test/toucan2/tools/after_select_test.clj
For `after-insert` and `after-select` methods
=> Tests to make sure `changes` and `original` are reset 

src/toucan2/connection.clj, src/toucan2/instance.clj, src/toucan2/jdbc/read.clj, src/toucan2/jdbc/result_set.clj, src/toucan2/jdbc/row.clj, src/toucan2/magic_map.clj, src/toucan2/tools/with_temp.clj, test/toucan2/instance_test.clj, test/toucan2/magic_map_test.clj, test/toucan2/tools/before_insert_test.clj, test/toucan2/tools/hydrate_test.clj, toucan1/src/toucan/models.clj, toucan1/test/toucan/models_test.clj
Transient Instance maps and MagicMaps didn't correctly handle cases where the maps passed the ArrayMap -> HashMap threshold. They discarded the values of transient functions like `assoc!`. Fix bugs with creating instances/magic maps with large numbers of keys.
Also misc code cleanup and extra tests.
=> Fix transient maps with large number of keys; fix transient magic map `dissoc!` not transforming keys

src/toucan2/tools/hydrate.clj, test/toucan2/tools/hydrate_test.clj
Rather than just the first key. Fixes issues doing batched hydration with sequences like `[nil []]`
=> Check first non-nil key for sequence-of-sequence hydration

src/toucan2/tools/hydrate.clj
in metabase
```
io.github.camsaul/toucan2                 {#_:mvn/version #_"1.0.516"
:local/root "/Users/dan/projects/work/toucan2"}
```
create a new pg database and sync it empty.
```clojure
(time
(let [conn (sql-jdbc.conn/db->pooled-connection-spec 3)]
(dotimes [n 359]
(jdbc/execute! conn [(format "create table if not exists foo_%d (id int, col_1 text, col_2 text, col_3 text, col_4 text, col_5 text, col_6 text, col_7 text, col_8 text, col_9 text, col_10 text, col_11 text, col_12 text, col_13 text, col_14 text)" n)]))))
(sync/sync-database! (db/select-one 'Database :id 3) {:scan :schema})
(binding [api/*current-user-permissions-set* (delay #{"/"})]
(count (#'metabase.api.database/db-metadata 3 true true)))
```
before patch:
```clojure
horror=> (binding …
```
=> recur with concat gives stack overflow bugs

README.md, src/toucan2/insert.clj, test/toucan2/insert_test.clj
In Metabase we relied on `insert!` returning the instance in various places and it's a little noisy replacing `(db/insert! foo)` with `(first (db/insert-returning-instances! foo))`. There's a similar story for `insert-returning-pks!`. So this PR just adds convenience functions to do that for you.
I pretty seriously looked into adding an `insert.pk` and `insert.instance` type and writing a `(m/defmethod pipeline/results-transform [:toucan.query-type/insert.pk ::transformed model] ... (comp first xf))` sort of thing, but then it started to feel like an awful lot of work for no clear benefit.
As written it obviously will just drop any instances/PKs apart from the first one, but if you think there should be a check to make sure that there's exactly one instance/PK that could happen.
=> Add insert-returning-pk! and insert-returning-instance!

src/toucan2/instance.clj, src/toucan2/jdbc/row.clj, src/toucan2/protocols.clj, test/toucan2/instance_test.clj, test/toucan2/jdbc/row_test.clj
Fixes #105
Also: 
- fix `contains?` for transient instances
- fix `contains?` when adding keys to transient rows
- simplify transient row type, remove unneeded atom
=> Fix `dissoc` with transient rows

src/toucan2/connection.clj, src/toucan2/jdbc/read.clj, src/toucan2/jdbc/result_set.clj, src/toucan2/model.clj, src/toucan2/pipeline.clj, src/toucan2/query.clj, src/toucan2/save.clj, src/toucan2/tools/after.clj, src/toucan2/tools/after_select.clj, src/toucan2/tools/before_insert.clj, src/toucan2/tools/default_fields.clj, src/toucan2/tools/with_temp.clj, src/toucan2/types.clj, test/toucan2/test.clj, toucan1/src/toucan/models.clj
=> Add `dispatch-value-spec`/`defmethod-arities` to multimethods without them

src/toucan2/instance.clj, src/toucan2/protocols.clj, test/toucan2/tools/after_update_test.clj
I might be missing something, but as far as I can see #129 has already been fixed. This adds a test that proves it.
I feel bad about the atom but couldn't think of a better way.
=> Add test for changes being available in after-update

src/toucan2/instance.clj, src/toucan2/jdbc/row.clj, src/toucan2/util.clj
Closes https://github.com/camsaul/toucan2/issues/164
There's some speculation here, perhaps we need to protect against some other custom map classes.
The use of a protocol is for two reasons:
1. Extensibility in the fringe case that toucan2's used in a application that implements custom maps from scratch.
2. Avoiding reflection on the check. Given that toucan2 is low down the stack its worth avoiding worthless extra work.
=> Avoid copying plain map when converting to instance

src/toucan2/instance.clj, test/toucan2/instance_test.clj
Without this, if kv-reduce is called on an Instance, the code follows the slow unoptimal path of calling 'reduce' on the map and constructing MapEntries.
This happens notably in Metabase in `instance->metadata` (https://github.com/metabase/metabase/blob/a43b09cdfed17151e4cd2dd34feeecb3f0e012f4/src/metabase/lib/metadata/jvm.clj#L47) but I've seen it in other places too.
=> Add native implementation for IKVReduce in toucan2.instance.Instance

.clj-kondo/com.github.seancorfield/next.jdbc/config.edn, .clj-kondo/com.github.seancorfield/next.jdbc/hooks/com/github/seancorfield/next_jdbc.clj_kondo, .github/workflows/tests.yml, deps.edn
Sean Corfield pushed a commit that fixes https://github.com/seancorfield/honeysql/issues/537 so we can use that for running Cloverage now.
Also switch to running Kondo with `clojure`/`deps.edn` so we don't need to download and install it in CI and can easily pin a specific version locally
=> Bump Honey SQL version & Use JVM Kondo

src/toucan2/tools/hydrate.clj
`m/effective-primary-method`, which was used in `can-hydrate-with-strategy?` to check if a particular hydration strategy is available for a model, constructs a primary method every time it is invoked. Instead, `m/effective-method` will try to lookup a cached method for the given dispatch value if the mm is a CachedMultiFnImpl (it is by default).
Note that caching only works for hits. If the method isn't implemented for a particular dispatch value, Methodical will go through the expensive process of trying to construct a method.
=> [hydrate] Use cached Methodical function to check for mm implementation

src/toucan2/log.clj
Currently, Toucan's logging macros always produce allocation overhead by converting between primitive ints and Integer objects. This change ensures that primitive arities are chosen, and hence, there are no allocations if the logging level mismatches the logging statement.
=> [log] Add primitive hints to logging level functions

src/toucan2/instance.clj
The function `toucan2.instance/update-original-and-current` appears to be frequently invoked inside `toucan2.tools.transformed/apply-result-row-transform`. The call chain involves passing `args` with `apply` in multiple functions, which generates redundant garbage (redundant because `apply-result-row-transform` doesn't pass any `args`, just `f`).
The PR adds an explicit f-only arity to functions in the call chain.
=> [instance] Provide non-vararg arity for update-original-and-current

src/toucan2/jdbc/read.clj, src/toucan2/jdbc/result_set.clj
=> [jdbc.read] Remove value caching from JDBC reading machinery

src/toucan2/jdbc/row.clj, test/toucan2/jdbc/row_test.clj
=> Make sure fetching column from transient row persists changes where needed

src/toucan2/jdbc/read.clj
Thanks to your comment on #179 I finally understood what is the deal with column thinks and such. This PR moves computing the thunk to where it should be – outside of the returned lambda, so that the machinery is not re-run for every row. The benchmark from #185 gives this:
```
master (results are reused):
Time per call: 18.89 ms   Alloc per call: 17,484,278b
Time per call: 18.90 ms   Alloc per call: 17,483,998b
Time per call: 18.87 ms   Alloc per call: 17,483,817b
After PR:
Time per call: 9.83 ms   Alloc per call: 11,968,423b   Iterations: 209
Time per call: 9.99 ms   Alloc per call: 11,968,262b   Iterations: 201
Time per call: 9.76 ms   Alloc per call: 11,968,255b   Iterations: 209
```
=> [jdbc.read] Properly pre-compute column fetching thunk

src/toucan2/jdbc/row.clj
This doesn't look much like an improvement but it actually removes two sources of allocations per each row – the LongRange and the lambda created by `partial`. This accounts for ~10% of allocations in my "select 10k rows" benchmark, and it costs nothing to optimize it (except maybe a bit of readability).
=> [jdbc.row] Reduce allocations in fetch-all-columns!

src/toucan2/jdbc/read.clj, src/toucan2/jdbc/result_set.clj, src/toucan2/jdbc/row.clj
As discussed in #184, this solution is simpler and more efficient than that PR if the approach is viable.
10k rows benchmark against current master:
```
master:
Time per call: 7.49 ms   Alloc per call: 11,088,805b
Time per call: 7.45 ms   Alloc per call: 11,088,041b
Time per call: 7.63 ms   Alloc per call: 11,087,626b
no per-cell traces (10% improvement):
Time per call: 6.74 ms   Alloc per call: 11,086,952b
Time per call: 6.73 ms   Alloc per call: 11,086,286b
Time per call: 6.73 ms   Alloc per call: 11,085,933b
No per-row traces (another 14% improvement):
Time per call: 5.63 ms   Alloc per call: 11,085,107b
Time per call: 5.83 ms   Alloc per call: 11,084,783b
Time per call: 5.63 ms   Alloc per call: 11,084,576b
```
At first I thought to remove only the per-cell traces but the per-row ones …
=> Comment out log traces

src/toucan2/jdbc/read.clj
I'll need your feedback on this PR as it's not as clear-cut as the other ones. `memoize` is quite inefficient on a per-call basis (either a hit or a miss). The cheapest (amortized) way to look up per-column thunks is to compute them early and put into a vector. This is the best thing to do for regular selects where the whole row is realized anyway. However, it may be doing unnecessary work for other types of select where only one column is extracted, or PKs, or whatever.
Still, the overhead would only happen once per ResultSet, not per each value cell like now. I'll defer to your judgement.
An alternative would be to roll out a custom memoize-like structure for this (e.g. vector in an atom).
=> [jdbc.row] Replace memoize in lazy thunk construction with delays

src/toucan2/tools/before_update.clj, test/toucan2/tools/after_update_test.clj, test/toucan2/tools/before_update_test.clj
In a very precise condition, we would emit an `UPDATE` clause without
any `WHERE` condition at all:
- the `before-update` method's result does not have a primary key
- the `where` clause in an `update!` call matches multiple rows
- some part of the update map will change all matched rows
- another part of the update map will change only a subset of matched
rows
If all these conditions are met, the bug is triggered and we emit an
UPDATE without any `WHERE` clause at all.
This fixes the issue by making sure to get the primary keys from the
realized row rather than from the result of
`(before-update (merge realized-row changes))`. I also added tests as
well as an assertion that a primary key is actually present, since its
absence is so dangerous.
=> Fix a footgun in `before-update`

src/toucan2/jdbc/mysql_mariadb.clj, src/toucan2/pipeline.clj, src/toucan2/select.clj, test/toucan2/execute_test.clj
According to my benchmarks, using transients here yields allocation advantage and some runtime boost as well. I'm not sure about the name of the new function, maybe it should be `with-transient-conj!-init` or something like that?
=> [select] Use transients in select-reducing functions

src/toucan2/tools/hydrate.clj, test/toucan2/tools/hydrate_test.clj
This hadn't been noticed previously since N is generally small, eg. 50 or 60 at most. Working with a Metabase dashboard that loaded 10000 fields (100 each from 100 tables) in a single `select` + `hydrate`, I found this was consuming about 3 seconds.
The slow path was effectively a very slow `conj`: taking the `acc` vector, and then for each `annotated-instances` doing:
```clojure
(recur (vec (concat acc nil [(first hydrated-instances)]))
...)
```
which is pouring the whole vector into a lazy sequence and back into a vector, once for each instance in the list.
The new version uses a custom transducer to do the same process in O(n) time (and without any seq overhead, as a bonus).
=> Fix an N^2 in batch hydration

src/toucan2/pipeline.clj
Another small but non-invasive improvement. This works best when many rows are processed, but shouldn't bring too much of an overhead if one/few rows are selected.
=> [pipeline] Use conj! as the default pipeline rf

src/toucan2/model.clj
`select-keys` is one of the criminally inefficient functions for no good reason (it uses `reduce1` which is terrible by its own). Combined with the fact that `toucan2.instance.Instance` doesn't provide a straightforward `entryAt` implementation, select-keys performs especially poorly on Toucan instances. This custom select-keys implementation is more efficient given the circumstances.
If necessary, this custom implementation can be extracted somewhere into util namespace. However; there are only a few `select-keys` usages across Toucan, and only this one is performance-sensitive.
=> [model] Use hand-rolled select-keys implementation

src/toucan2/tools/with_temp.clj
Replacing a normal string in `testing` with a delayed CharSequence implementation (introduced in #197) caused problems with Cursive (which seemingly doesn't call `str` on the `*testing-context*` elements).
To fix it, this PR undoes the `delayed-string` thing and also stops adding attributes to printed testing context.
Disussion: https://metaboat.slack.com/archives/CKZEMT1MJ/p1747411379195139
=> [with-temp] Remove delayed-string and printing overridden attributes altogether
